### ISSUE TITLE
README installation guide

### ISSUE THREAD

**Issue by jshin49** [j-min/dotfiles#1]
In the README instructions, I think you should fix the following line

```
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
```

to 

```
alias dot='/usr/bin/git --git-dir=$HOME/dotfiles.git/ --work-tree=$HOME'
```

**Comment by j-min** [comment]
You can choose your own name for the git directory.
I chose `.dotfiles`, since I didn't want to reveal the git directory in default setting.
In fact, git bare cloning was inspired from [this tutorial](https://www.atlassian.com/git/tutorials/dotfiles) (they used `.cfg` for the git directory name).
If there's any pros for using non-dot-name for the directory, let me know.

**Comment by jshin49** [comment]
The reason I had to use ```dotfiles.git``` for the git directory is because I was receiving an error saying 'not a git repository' when performing ```dot checkout```. Any ideas why?

**Comment by j-min** [comment]
Did you use `--bare` option when cloning?

**Comment by jshin49** [comment]
Yes.

I ran the bare option to create ```dotfiles.git```.

**Comment by j-min** [comment]
Did you do `git clone --bare https://github.com/j-min/dotfiles $HOME/dotfiles`
or `git clone --bare https://github.com/j-min/dotfiles $HOME/.dotfiles`?

You might have edited the directory name when cloning.

**Comment by jshin49** [comment]
You're right. I found the issue.

I accidentally neglected ```$HOME/.dotfiles```

from the git clone command.

Thanks!

**Comment by j-min** [comment]
Glad that you resolved the issue! 😃
